language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer self-update
  - composer install --prefer-dist

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/coveralls
